version: '3'
services:
  nginx:
    image: nginx:1.21
    ports:
      - 80:80
    volumes:
      - ./log/nginx:/var/log/nginx
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.3
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
      - ./log:/var/log
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms500m -Xmx500m
    restart: always
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.4.3
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
      - ./log:/var/log
    links:
      - elasticsearch:elasticsearch
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.4.3
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    restart: always
